import type { Layouts } from 'react-grid-layout'

export const HUB_DEFAULT_LAYOUTS: Layouts = {
  lg: [
    { i: 'todos', x: 0, y: 0, w: 4, h: 7, minW: 3, minH: 5 },
    { i: 'goals', x: 4, y: 0, w: 4, h: 7, minW: 3, minH: 5 },
    { i: 'notes', x: 8, y: 0, w: 4, h: 7, minW: 3, minH: 5 },
    { i: 'ideas', x: 0, y: 7, w: 4, h: 6, minW: 3, minH: 4 },
    { i: 'music', x: 4, y: 7, w: 4, h: 6, minW: 3, minH: 4 },
    { i: 'certificates', x: 8, y: 7, w: 4, h: 6, minW: 3, minH: 4 },
    { i: 'performance', x: 0, y: 13, w: 6, h: 6, minW: 4, minH: 4 },
    { i: 'timeline', x: 6, y: 13, w: 6, h: 6, minW: 4, minH: 4 },
    { i: 'logs', x: 0, y: 19, w: 4, h: 5, minW: 3, minH: 4 },
    { i: 'dev', x: 4, y: 19, w: 4, h: 5, minW: 3, minH: 4 },
    { i: 'ai-logs', x: 8, y: 19, w: 4, h: 5, minW: 3, minH: 4 },
    { i: 'ai-chat', x: 0, y: 24, w: 6, h: 6, minW: 4, minH: 5 },
    { i: 'calendar', x: 6, y: 24, w: 6, h: 6, minW: 4, minH: 5 },
    { i: 'level', x: 0, y: 30, w: 4, h: 5, minW: 3, minH: 3 },
    { i: 'date-highlight', x: 4, y: 30, w: 4, h: 5, minW: 3, minH: 3 },
    { i: 'weather', x: 8, y: 30, w: 4, h: 5, minW: 3, minH: 3 },
    { i: 'class-schedule', x: 0, y: 35, w: 4, h: 6, minW: 3, minH: 4 },
    { i: 'canvas-announcements', x: 4, y: 35, w: 4, h: 6, minW: 3, minH: 4 },
    { i: 'screen-time', x: 8, y: 35, w: 4, h: 6, minW: 3, minH: 4 },
    { i: 'assignments', x: 0, y: 41, w: 6, h: 6, minW: 4, minH: 5 },
    { i: 'github', x: 6, y: 41, w: 6, h: 6, minW: 4, minH: 5 },
    { i: 'ai-websites', x: 0, y: 47, w: 4, h: 5, minW: 3, minH: 3 },
    { i: 'school-links', x: 4, y: 47, w: 4, h: 5, minW: 3, minH: 3 },
    { i: 'quick-links', x: 8, y: 47, w: 4, h: 5, minW: 3, minH: 3 },
    { i: 'site-buttons', x: 0, y: 52, w: 6, h: 5, minW: 4, minH: 3 },
    { i: 'spotify-now', x: 6, y: 52, w: 6, h: 5, minW: 4, minH: 3 },
  ],
  md: [
    { i: 'todos', x: 0, y: 0, w: 5, h: 7 },
    { i: 'goals', x: 5, y: 0, w: 5, h: 7 },
    { i: 'notes', x: 0, y: 7, w: 5, h: 6 },
    { i: 'ideas', x: 5, y: 7, w: 5, h: 6 },
    { i: 'music', x: 0, y: 13, w: 5, h: 6 },
    { i: 'certificates', x: 5, y: 13, w: 5, h: 6 },
    { i: 'performance', x: 0, y: 19, w: 5, h: 6 },
    { i: 'timeline', x: 5, y: 19, w: 5, h: 6 },
    { i: 'logs', x: 0, y: 25, w: 5, h: 5 },
    { i: 'dev', x: 5, y: 25, w: 5, h: 5 },
    { i: 'ai-logs', x: 0, y: 30, w: 10, h: 5 },
    { i: 'ai-chat', x: 0, y: 35, w: 5, h: 6 },
    { i: 'calendar', x: 5, y: 35, w: 5, h: 6 },
    { i: 'level', x: 0, y: 41, w: 3, h: 5 },
    { i: 'date-highlight', x: 3, y: 41, w: 4, h: 5 },
    { i: 'weather', x: 7, y: 41, w: 3, h: 5 },
    { i: 'class-schedule', x: 0, y: 46, w: 5, h: 6 },
    { i: 'canvas-announcements', x: 5, y: 46, w: 5, h: 6 },
    { i: 'screen-time', x: 0, y: 52, w: 5, h: 6 },
    { i: 'assignments', x: 5, y: 52, w: 5, h: 6 },
    { i: 'github', x: 0, y: 58, w: 10, h: 6 },
    { i: 'ai-websites', x: 0, y: 64, w: 3, h: 5 },
    { i: 'school-links', x: 3, y: 64, w: 4, h: 5 },
    { i: 'quick-links', x: 7, y: 64, w: 3, h: 5 },
    { i: 'site-buttons', x: 0, y: 69, w: 5, h: 5 },
    { i: 'spotify-now', x: 5, y: 69, w: 5, h: 5 },
  ],
}
